# Generated by Django 5.0.6 on 2024-06-22 21:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0003_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="content",
            field=models.TextField(verbose_name="Məzmun"),
        ),
    ]
