# Generated by Django 5.0.6 on 2024-06-25 21:58

import ckeditor.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("posts", "0005_contactmessage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="content",
            field=models.TextField(verbose_name="Content"),
        ),
        migrations.AlterField(
            model_name="posts",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Author",
            ),
        ),
        migrations.AlterField(
            model_name="posts",
            name="content",
            field=ckeditor.fields.RichTextField(verbose_name="Content"),
        ),
        migrations.AlterField(
            model_name="posts",
            name="image",
            field=models.FileField(
                blank=True, null=True, upload_to="Post Images", verbose_name="İmage"
            ),
        ),
        migrations.AlterField(
            model_name="posts",
            name="title",
            field=models.CharField(max_length=200, verbose_name="Title"),
        ),
    ]
